bases:
  - ../../base
resources:
  - traefik-secret.yaml
patches:
  - traefik-ingressroute.yaml
  - traefik-persistentvolumeclaim.yaml
  - traefik-configmap.yaml
patchesJson6902:
- target:
    version: v1 # apiVersion
    kind: Service
    name: traefik-ingress
  path: patch-ports-services.yaml
